package com.dataAnalysis.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("algorithm", "Aid", Algorithm.class);
		arp.addMapping("database", "Dbid", Database.class);
		arp.addMapping("department", "Did", Department.class);
		arp.addMapping("table", "Tid", Table.class);
		arp.addMapping("user", "Uid", User.class);
		arp.addMapping("usertable", "Utid", Usertable.class);
	}
}

