package com.dataAnalysis.model;

import com.dataAnalysis.model.base.BaseAlgorithm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Algorithm extends BaseAlgorithm<Algorithm> {
	public static final Algorithm dao = new Algorithm().dao();
}
