package com.dataAnalysis.model;

import com.dataAnalysis.model.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department().dao();
}
