package com.dataAnalysis.model;

import com.dataAnalysis.model.base.BaseUsertable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usertable extends BaseUsertable<Usertable> {
	public static final Usertable dao = new Usertable().dao();
}
