package com.dataAnalysis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setDid(java.lang.String Did) {
		set("Did", Did);
	}

	public java.lang.String getDid() {
		return get("Did");
	}

	public void setDname(java.lang.String Dname) {
		set("Dname", Dname);
	}

	public java.lang.String getDname() {
		return get("Dname");
	}

	public void setDaddtime(java.util.Date Daddtime) {
		set("Daddtime", Daddtime);
	}

	public java.util.Date getDaddtime() {
		return get("Daddtime");
	}

}
