package com.dataAnalysis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlgorithm<M extends BaseAlgorithm<M>> extends Model<M> implements IBean {

	public void setAid(java.lang.String Aid) {
		set("Aid", Aid);
	}

	public java.lang.String getAid() {
		return get("Aid");
	}

	public void setAname(java.lang.String Aname) {
		set("Aname", Aname);
	}

	public java.lang.String getAname() {
		return get("Aname");
	}

	public void setAjarname(java.lang.String Ajarname) {
		set("Ajarname", Ajarname);
	}

	public java.lang.String getAjarname() {
		return get("Ajarname");
	}

	public void setAurl(java.lang.String Aurl) {
		set("Aurl", Aurl);
	}

	public java.lang.String getAurl() {
		return get("Aurl");
	}

	public void setAplatform(java.lang.Integer Aplatform) {
		set("Aplatform", Aplatform);
	}

	public java.lang.Integer getAplatform() {
		return get("Aplatform");
	}

	public void setAdescription(java.lang.String Adescription) {
		set("Adescription", Adescription);
	}

	public java.lang.String getAdescription() {
		return get("Adescription");
	}

	public void setAaddtime(java.util.Date Aaddtime) {
		set("Aaddtime", Aaddtime);
	}

	public java.util.Date getAaddtime() {
		return get("Aaddtime");
	}

}
