package com.dataAnalysis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUid(java.lang.String Uid) {
		set("Uid", Uid);
	}

	public java.lang.String getUid() {
		return get("Uid");
	}

	public void setUsername(java.lang.String Username) {
		set("Username", Username);
	}

	public java.lang.String getUsername() {
		return get("Username");
	}

	public void setUname(java.lang.String Uname) {
		set("Uname", Uname);
	}

	public java.lang.String getUname() {
		return get("Uname");
	}

	public void setUsex(java.lang.Integer Usex) {
		set("Usex", Usex);
	}

	public java.lang.Integer getUsex() {
		return get("Usex");
	}

	public void setUdepartment(java.lang.String Udepartment) {
		set("Udepartment", Udepartment);
	}

	public java.lang.String getUdepartment() {
		return get("Udepartment");
	}

	public void setUphone(java.lang.String Uphone) {
		set("Uphone", Uphone);
	}

	public java.lang.String getUphone() {
		return get("Uphone");
	}

	public void setUpassword(java.lang.String Upassword) {
		set("Upassword", Upassword);
	}

	public java.lang.String getUpassword() {
		return get("Upassword");
	}

	public void setUstate(java.lang.Integer Ustate) {
		set("Ustate", Ustate);
	}

	public java.lang.Integer getUstate() {
		return get("Ustate");
	}

	public void setUaddtime(java.util.Date Uaddtime) {
		set("Uaddtime", Uaddtime);
	}

	public java.util.Date getUaddtime() {
		return get("Uaddtime");
	}

	public void setUtype(java.lang.Integer Utype) {
		set("Utype", Utype);
	}

	public java.lang.Integer getUtype() {
		return get("Utype");
	}

}
